# Funding options for Orion Agent
# These links appear in the "Sponsor" button on GitHub

# Custom funding links (PayFast)
custom:
  - "https://payf.st/jkza6"
  - "https://payf.st/vhjfz"
  - "https://payf.st/qil2v"
